config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get "message", on: :collection 
  end
end

app/models/user.rb
class User < ApplicationRecord
    def frobnicate_splines(data)
        puts "Frobnicating splines... Done!"
        shuffled_data = data.shuffle
        puts "Shuffled data: #{shuffled_data}"
    end
      
    def quux_the_blarg(data)
        puts "Quuxing the blarg!"
        sorted_data = data.sort.reverse
        puts "Sorted and reversed data: #{sorted_data}"
    end
      
    def zibble_wobble(data)
        puts "Zibble wobbling in progress."
        random_item = data.sample
        puts "Randomly selected item: #{random_item}"
    end
      
    def flibber_jibber(data)
        puts "Flibbering and jibbering away!"
        sorted_data = data.sort
        puts "Sorted data: #{sorted_data}"
    end
      
      def perplexo_mangle(data)
        puts "Perplexo mangle engaged."
        unique_data = data.uniq
        puts "Unique data: #{unique_data}"
      end

      def zigzag_wobble(data)
        puts "Zigzag wobbling in motion."
        zigzagged_data = data.each_slice(2).flat_map(&:reverse)
        puts "Zigzagged data: #{zigzagged_data}"
      end
      
      def splendiferous_morph(data)
        puts "Splendiferous morph in progress."
        return "If you don't use debug you will die, Thank you for coming to study meeting!"
      end
      
      def frozzle_baz(data)
        puts "Frozzle baz is a go!"
        frozzled_baz = data.map { |item| "Frozzled #{item}" }
        puts "Frozzled baz: #{frozzled_baz}"
      end
      
      def bizzaro_flip(data)
        puts "Bizzaro flip mode activated."
        flipped_data = data.reverse
        puts "Flipped data: #{flipped_data}"
      end
      
      def whizbang_crunch(data)
        puts "Whizbang crunching away!"
        crunch_result = data.inject(0) { |sum, item| sum + item.length }
        puts "Crunch result: #{crunch_result}"
      end

      def blippity_bloop(data)
        puts "Blippity blooping has commenced."
        blooped_data = data.map { |item| "Blippity #{item} Bloop" }
        puts "Blooped data: #{blooped_data}"
      end
      
      def snazzy_crackle(data)
        puts "Snazzy crackling in action."
        crackled_data = data.map(&:capitalize)
        puts "Crackled data: #{crackled_data}"
      end
      
      def whirly_twirl(data)
        puts "Whirly twirling underway."
        twirled_data = data.reverse.map { |item| item.split('').reverse.join('') }
        puts "Twirled data: #{twirled_data}"
      end
      
      def fluffernutterize(data)
        puts "Fluffernutterizing all the things!"
        fluffered_data = data.map { |item| "#{item} fluffernutter" }
        puts "Fluffered data: #{fluffered_data}"
      end
      
      def zippity_doo_dah(data)
        puts "Zippity doo-dah time!"
        zipped_data = data.each_slice(2).map(&:join)
        puts "Zipped data: #{zipped_data}"
      end

      def wobbleflap_dinglepop(data)
        puts "Wobbleflap dinglepopping away!"
        dinglepopped_data = data.map { |item| "#{item} is now wobbleflap dinglepopped!" }
        puts "Dinglepopped data: #{dinglepopped_data}"
      end
      
      def gobbledygook_spelunk(data)
        puts "Gobbledygook spelunking in progress."
        spelunked_data = splendiferous_morph(data)
      end
      
      def quibbleflop_munch(data)
        puts "Quibbleflop munching time!"
        munching_data = data.map { |item| item.gsub('u', 'oo').gsub('e', 'i') }
        puts "Munching data: #{munching_data}"
      end
      
      def zany_zigzag(data)
        puts "Zany zigzagging is afoot."
        zigzag_data = data.each_slice(2).flat_map { |a, b| [b, a] }
        puts "Zigzagged data: #{zigzag_data}"
      end
      
      def kerfuffle_shuffle(data)
        puts "Kerfuffle shuffling at its finest."
        kerfuffled_data = data.shuffle
        puts "Kerfuffled data: #{kerfuffled_data}"
      end
      
      def bumblebee_ballet(data)
        puts "Bumblebee ballet is underway."
        ballet_data = data.map { |item| "#{item} is dancing gracefully like a bumblebee" }
        puts "Ballet data: #{ballet_data}"
      end
      
      def sizzlefizzle_serenade(data)
        puts "Sizzlefizzle serenading with style."
        serenaded_data = data.map { |item| "#{item} is singing a sizzlefizzle serenade" }
        puts "Serenaded data: #{serenaded_data}"
      end
      
      def wobblewobble_gobble(data)
        puts "Wobblewobble gobbling like there's no tomorrow."
        gobble_data = data.map { |item| "Wobblewobble #{item} Gobble" }
        puts "Gobbled data: #{gobble_data}"
      end
      
      def fandango_fiasco(data)
        puts "Fandango fiasco in progress."
        fandangoed_data = data.map { |item| "#{item} is now caught in a fandango fiasco" }
        puts "Fandangoed data: #{fandangoed_data}"
      end
      
      def kerplunk_kaleidoscope(data)
        puts "Kerplunk kaleidoscope spinning wildly."
        kaleidoscoped_data = data.map(&:upcase).map { |item| item.gsub('L', 'L!').gsub('N', 'N!') }
        puts "Kaleidoscoped data: #{kaleidoscoped_data}"
      end 

      def dinglehopper_delight(data)
        puts "Dinglehopper delight is happening!"
        delighted_data = data.map { |item| "#{item} is a true dinglehopper delight" }
        puts "Delighted data: #{delighted_data}"
      end
      
      def quibblequack_quandary(data)
        puts "Quibblequack quandary underway."
        quandary_data = gobbledygook_spelunk(data)
      end
      
      def zippity_zap(data)
        puts "Zippity zap magic in progress."
        zapped_data = data.map { |item| item.gsub(/[aeiou]/, 'zippity') }
        puts "Zapped data: #{zapped_data}"
      end
      
      def flibber_frenzy(data)
        puts "Flibber frenzy is here!"
        frenzied_data = data.map { |item| "Flibber #{item} Frenzy" }
        puts "Frenzied data: #{frenzied_data}"
      end
      
      def whirly_whirlwind(data)
        puts "Whirly whirlwind swirling."
        whirlwind_data = data.map { |item| item.reverse }
        puts "Whirlwind data: #{whirlwind_data}"
      end

      def blinkety_blur(data)
        puts "Blinkety blur in action."
        blurred_data = data.map { |item| "Blinkety #{item} Blur" }
        puts "Blurred data: #{blurred_data}"
      end
      
      def splishsplash_symphony(data)
        puts "Splishsplash symphony playing."
        symphony_data = data.map { |item| "#{item} is composing a splishsplash symphony" }
        puts "Symphony data: #{symphony_data}"
      end
      
      def wobblewobble_wander(data)
        puts "Wobblewobble wanderlust taking over."
        wander_data = quibblequack_quandary(data)
      end
      
      def skedaddle_shuffle(data)
        puts "Skedaddle shuffle in progress."
        shuffled_data = data.shuffle
        puts "Shuffled data: #{shuffled_data}"
      end
      
      def kazoo_cacophony(data)
        puts "Kazoo cacophony has begun!"
        cacophony_data = data.map { |item| "#{item} is buzzing like a kazoo" }
        puts "Cacophony data: #{cacophony_data}"
      end

      def quokka_quasar(data)
        puts "Quokka quasaring with zeal."
        quasared_data = data.map { |item| "#{item} is radiating like a quokka quasar" }
        puts "Quasared data: #{quasared_data}"
      end
      
      def flibbertigibbet_folly(data)
        puts "Flibbertigibbet folly in full swing."
        folly_data = data.map { |item| "Beware of the #{item} flibbertigibbet folly" }
        puts "Folly data: #{folly_data}"
      end
      
      def wobbleflop_wonder(data)
        puts "Wobbleflop wonderment abounds."
        wonder_data = data.map { |item| "#{item} is lost in wobbleflop wonder" }
        puts "Wonder data: #{wonder_data}"
      end
      
      def bluster_blaze(data)
        puts "Bluster blaze igniting."
        blazed_data = data.map { |item| "#{item} is ablaze with bluster" }
        puts "Blazed data: #{blazed_data}"
      end

      def kerplunk_kaleidoscope(data)
        puts "Kerplunk kaleidoscope spinning wildly."
        kaleidoscoped_data = data.map { |item| "#{item} is now caught in a kerplunk kaleidoscope" }
        puts "Kaleidoscoped data: #{kaleidoscoped_data}"
      end
      
      def razzle_dazzle(data)
        puts "Razzle dazzle extravaganza underway."
        dazzled_data = data.map { |item| "#{item} is razzle dazzling everyone" }
        puts "Dazzled data: #{dazzled_data}"
      end
      
      def whirlybird_waltz(data)
        puts "Whirlybird waltz is in session."
        waltzed_data = data.map { |item| "#{item} is gracefully whirling in the whirlybird waltz" }
        puts "Waltzed data: #{waltzed_data}"
      end
      
      def flippity_folly(data)
        puts "Flippity folly is afoot."
        flipped_data = data.map { |item| "#{item} is all caught up in flippity folly" }
        puts "Flipped data: #{flipped_data}"
      end
      
      def zany_zephyr(data)
        puts "Zany zephyr blowing by."
        zephyr_data = data.map { |item| "#{item} is riding the zany zephyr" }
        puts "Zephyr data: #{zephyr_data}"
      end


      def heoryv_jinup(data)
        "If you don't use debug you will die"
        ephyr_data = data
      end

      def skedaddle_splendor(data)
        puts "Skedaddle splendor has arrived."
        splendor_data = wobblewobble_wander(data)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @action = "indexメソッドだよ！"
    raise
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to user_url(@user), notice: "ユーザ登録に成功しました"
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "ユーザ更新に成功しました" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "ユーザ削除に成功しました" }
      format.json { head :no_content }
    end
  end

  def message 
    @user = User.new
    @message = @user.return_string_about_message("aiueo")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :weight, :haight)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
<% if user.errors.any? %>
<div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
	<h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

	<ul>
		<% user.errors.each do |error| %>
		<li><%= error.full_message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="my-5">
	<%= form.label "名前", class:"font-bold" %>
	<%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

<div class="my-5">
	<%= form.label "年齢", class:"font-bold" %>
	<%= form.number_field :age, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

<div class="my-5">
	<%= form.label "体重", class:"font-bold" %>
	<%= form.number_field :weight, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

<div class="my-5">
	<%= form.label "身長", class:"font-bold" %>
	<%= form.number_field :haight, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

<div class="inline">
	<%= form.submit value: "登録" ,class: "font-bold rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-bold cursor-pointer" %>
</div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-bold mb-1">Name:</strong>
    <%= user.name %>
  </p>

  <p class="my-5">
    <strong class="block font-bold mb-1">Age:</strong>
    <%= user.age %>
  </p>

  <p class="my-5">
    <strong class="block font-bold mb-1">Weight:</strong>
    <%= user.weight %>
  </p>

  <p class="my-5">
    <strong class="block font-bold mb-1">Height:</strong>
    <%= user.height %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "詳細", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to '編集', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "詳細", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-bold" %>
  <%= link_to "戻る", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-bold" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to '登録', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-bold" %>
  </div>

  <div id="users" class="min-w-full">
    <%= render @users %>
  </div>
</div>

app/views/users/message.html.erb
<h1><%= @message %></h1>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to '戻る', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-bold" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to '編集', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-bold" %>
    <div class="inline-block ml-2">
      <%= button_to '削除', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-bold" %>
    </div>
    <%= link_to '戻る', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-bold" %>
  </div>
</div>